apiVersion: apps/v1
kind: Deployment
metadata:
  name: refund-agent-deployment
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: refund-agent
  template:
    metadata:
      labels:
        app: refund-agent
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: refund-agent-sa
      containers:
        - name: refund-agent
          image: ai200stephenacr.azurecr.io/refund-service:latest
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: refund-agent-config

          resources: 
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi" 

          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 30 
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3 

          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          

          